version: '3.3'
services:
  pilipala:
    image: cxyjerry/pilipala:v1.0.0
    ports:
      - "8090:8080"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/pilipala/log:/usr/log/
      - /home/pilipala/upload-dir:/usr/pilipala/target/upload-dir
      - /home/pilipala/application-prod.yml:/app/application-prod.yml
    networks:
      - my-network
networks:
  my-network:
    driver: bridge