version: '3.3'
services:
  pilipala:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /home/pilipala/:/
      - /home/pilipala/log:/usr/log/
      - /home/pilipala/upload-dir:/usr/pilipala/target/upload-dir
    networks:
      - my-network
networks:
  my-network:
    driver: bridge