server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.jerry.pilipala.interfaces.web

knife4j:
  enable: true
  setting:
    language: zh_cn

spring:
  profiles:
    active: @activatedProperties@
  mvc:
    async:
      request-timeout: -1

logging:
  config: classpath:logback-spring.xml

limit:
  ip-max-count: 100