server:
  port: 8080
swagger:
  config:
    base-package: com.jerry.pilipala.interfaces.web

spring:
  profiles:
    active: @activatedProperties@

logging:
  config: classpath:logback-spring.xml

limit:
  ip-max-count: 100