file:
  work-dir: D:/MyDataArea/OpenSource/pilipala/target/upload-dir

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/pilipala
    neo4j:
      database: neo4j
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  session:
    timeout: 3600
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: jerry666
    connection-timeout: 60s
    pool:
      max-connection-lifetime: 24h
  mail:
    host: smtp.qq.com
    username: xxx@qq.com
    password: xxxxx
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
logging:
  level:
    org.springframework.data.mongodb.core: debug

sa-token:
  token-name: 'pilipala'
  timeout: 2592000
  active-timeout: -1
  is-concurrent: false
  is-share: false
  token-style: uuid
  is-log: true
sms:
  access-key: 7moGTMnPKZDcXF9RNGrujK3fY
  signature: PiliPala